name: 'Cerbos Setup Action'
description: 'Setups cerbos by downloading and adding to the path'
author: 'Cerbos'

inputs:
  github_token:
    description: 'The GitHub token to use'
    required: false
  version:
    description: 'Cerbos tooling version to download'
    required: true
    default: 'latest'

runs:
  using: 'node20'
  main: 'dist/index.js'
