name: 'Cerbos Setup Action'
description: 'Sets up Cerbos and Cerbosctl binaries into PATH'
author: 'Cerbos'

inputs:
  github_token:
    description: 'The GitHub token to use'
    required: false

  version:
    description: 'Cerbos and Cerbosctl version to download'
    required: true
    default: 'latest'


runs:
  using: 'node24'
  main: './dist/index.js'
